### ISSUE TITLE
Not working with Angular 8

### ISSUE THREAD

**Issue by stephanecot** [captcha-com/angular-captcha#5]
The error:
Uncaught Error: Can't resolve all parameters for CorrectCaptchaDirective: (?, [object Object])...

It seams that the import:
import { DOCUMENT } from '@angular/platform-browser';

has changed to:
import { DOCUMENT } from '@angular/common';

**Comment by botdetect-support** [comment]
The issue is fixed in the Angular Captcha Module v3.6.0.

Run the following command to get the latest version:

> npm i angular-captcha@latest

Thanks for reporting the issue!
If you have any further questions, please feel free to contact us at: https://captcha.com/contact.html

**Comment by stephanecot** [comment]
There're still an error when compiling in prod mode:

 Function calls are not supported in decorators but 'provideBotDetectCaptcha' was called in 'BotDetectCaptchaModule'
    'BotDetectCaptchaModule' calls 'provideBotDetectCaptcha'.

**Comment by botdetect-support** [comment]
Thanks for your report. We are working on it and will notify you once the issue is fixed.
To avoid this issue you can use the following approach:

After you import Angular Captcha Module in your app.module.ts:

```
// import the Angular Captcha Module 
import { BotDetectCaptchaModule } from 'angular-captcha'; 
 
@NgModule({
  imports: [
    ...
    BotDetectCaptchaModule
  ],
  ...
})
```

set the captchaEndpoint in your component:

```
import { CaptchaComponent } from 'angular-captcha'; 
 
export class YourFormWithCaptchaComponent {

  @ViewChild(CaptchaComponent, { static: true }) captchaComponent: CaptchaComponent;
 
  ngOnInit(): void {
    this.captchaComponent.captchaEndpoint = 
      // if you have asp.net on backend
      'https://your-app-backend-hostname.your-domain.com/simple-captcha-endpoint.ashx';
      
      // if you have java on backend
      // 'https://your-app-backend-hostname.your-domain.com/simple-captcha-endpoint';
      
      // if you have php on backend
      //'https://your-app-backend-hostname.your-domain.com/botdetect-captcha-lib/simple-botdetect.php';
  }
```

**Comment by botdetect-support** [comment]
@stephanecot The compilation issue is fixed in the Angular Captcha Module v3.7.0.

Run the following command to get the latest version:

> npm i angular-captcha@latest

**Comment by stephanecot** [comment]
Thanks!

Le mer. 5 juin 2019 à 10:29, botdetect-support <notifications@github.com> a
écrit :

**Comment by stephanecot** [comment]
It's working, but I found another smalll problem.
I have a core module and some child modules.

You need to move the declaration of:
<code>
providers: [
    CaptchaService,
    CaptchaHelperService,
    CaptchaEndpointPipe,
..}
</code>

into the forRoot() method and not to keep them into the general module,  because, it make mandatory to use the forChild() method for each features modules which used the captcha module. 

If the forChild() method is not used (ie no config is set), the previous root config is never used as the services are re-created in the child.
